### ISSUE TITLE
Configurar despliegue en Firebase con GitHub Actions

### ISSUE THREAD

**Issue by dangarbar** [dangarbar/portfolio-angular#8]
Automatizar el despliegue de la aplicación en Firebase mediante GitHub Actions.

**Comment by dangarbar** [comment]
# 🚀 Configurar despliegue en Firebase con GitHub Actions

## 📌 Objetivo  
Automatizar el despliegue de la aplicación Angular en **Firebase Hosting** utilizando **GitHub Actions**.

---

## 🔹 Pasos para completar la tarea  

### 1️⃣ Instalar la CLI de Firebase  
Ejecuta el siguiente comando para instalar la CLI de Firebase en tu máquina local:  

```bash
npm install -g firebase-tools
```

Inicia sesión en Firebase:  

```bash
firebase login
```

---

### 2️⃣ Configurar Firebase en el proyecto  
Inicializa Firebase en tu proyecto ejecutando:  

```bash
firebase init
```

📌 **Opciones a seleccionar:**  
1. Selecciona **Hosting**.  
2. Selecciona el proyecto Firebase asociado.  
3. Define `dist/portfolio-angular` como el directorio público.  
4. Elige **No** cuando pregunte si deseas configurar una aplicación de una sola página (SPA).  

Esto generará el archivo `firebase.json` en la raíz del proyecto.

---

### 3️⃣ Configurar el Token de Firebase en GitHub  
1. Genera un token de autenticación con el siguiente comando:  

   ```bash
   firebase login:ci
   ```

2. Copia el token y guárdalo en **GitHub → Settings → Secrets and variables → Actions** como `FIREBASE_TOKEN`.  

---

### 4️⃣ Crear el workflow de GitHub Actions  
Crea la carpeta de workflows en el proyecto:  

```bash
mkdir -p .github/workflows
```

Crea el archivo `.github/workflows/deploy.yml`:  

```bash
touch .github/workflows/deploy.yml
```

Agrega la siguiente configuración en `deploy.yml`:  

```yaml
name: Deploy Angular App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout del código
        uses: actions/checkout@v3

      - name: 🔧 Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Instalar Angular CLI y dependencias
        run: |
          npm install -g @angular/cli
          npm install

      - name: 🏗 Construir la aplicación
        run: ng build --configuration production

      - name: 🚀 Desplegar en Firebase
        run: npx firebase deploy --token=${{ secrets.FIREBASE_TOKEN }}
```

---

### 5️⃣ Subir cambios y probar el workflow  
Confirma los cambios y súbelos a GitHub:  

```bash
git add .
git commit -m "🚀 Configuración de despliegue automático en Firebase"
git push origin main
```

📌 Esto activará automáticamente el workflow en **GitHub Actions** y desplegará la aplicación en **Firebase Hosting**.

---

## 📌 Criterios de finalización de la tarea  
✅ **Firebase Hosting está configurado en el proyecto.**  
✅ **El token de Firebase está almacenado en GitHub Secrets.**  
✅ **El workflow de GitHub Actions automatiza el despliegue en Firebase.**  
✅ **Un push a `main` activa el despliegue automáticamente.**  
✅ **Los cambios están subidos al repositorio en GitHub.**
